<?php

namespace rgen3\tickets\widgets;

use rgen3\tickets\models\TicketMessage;
use rgen3\tickets\models\TicketTheme;
use yii\base\Widget;

class UnreadMessages extends Widget
{
    private $userId = null;

    public function init()
    {
        parent::init(); // TODO: Change the autogenerated stub
        if (is_null($this->userId))
        {
            $this->userId = \Yii::$app->user->id;
        }
    }

    protected function count()
    {
        $query = TicketTheme::find()
            ->where(['is_new' => 1, 'user_from' => $this->userId])
            ->joinWith('unreadMessages', true);

        return $query->count();
    }

    protected function getThemes()
    {
        $query = TicketTheme::find()
            ->where(['user_from' => $this->userId])
            ->orderBy(['updated_at' => SORT_DESC])
            ->limit(3)
        ;

        return $query->all();
    }


    public function run()
    {
        return $this->render('@frontend/views/widgets/unread_messages/dropdown.php',
            [
                'unreadMessages' => $this->count(),
                'latestMessages' => $this->getThemes()
            ]
        );
    }
}