<?php

namespace rgen3\tickets\widgets;

use rgen3\tickets\models\TicketMessage;
use rgen3\tickets\models\TicketTheme;
use yii\base\Widget;

class UnreadMessages extends Widget
{
    private $userId = null;

    public function init()
    {
        parent::init(); // TODO: Change the autogenerated stub
        if (is_null($this->userId))
        {
            $this->userId = \Yii::$app->user->id;
        }
    }

    public function count()
    {
        $query = TicketTheme::find()
            ->where(['is_new' => 1, 'user_from' => $this->userId])
            ->joinWith('unreadMessages', true);

        return $query->count();
    }

    public function run()
    {
        return $this->count();
    }
}