<?php

namespace rgen3\tickets\models\forms;

use common\models\User;
use rgen3\tickets\models\TicketMessage;
use rgen3\tickets\models\TicketTheme;
use rgen3\tickets\Module;
use rgen3\tickets\traits\UserFrom;
use yii\base\Model;
use yii\helpers\ArrayHelper;

class CreateTicket extends Model
{
    use UserFrom;

    public $dialogId;
    public $subject;
    public $message;
    public $status;

    private $assignedTo;

    public function init()
    {
        parent::init(); // TODO: Change the autogenerated stub
        $this->setUserFrom();
        $this->setAssignedTo();
    }

    public function setAssignedTo()
    {
        $this->assignedTo = 1;
    }

    public function getAssignedTo()
    {
        return $this->assignedTo;
    }

    public function rules()
    {
        $userModel = Module::$userModel;
        $rules = [
            [['subject', 'message'], 'required'],
            [['subject', 'message'], 'safe'],
            [['subject', 'message'], 'filter', 'filter' => function($value){
                $value = strip_tags($value);
                $value = htmlentities($value);
                $value = trim($value);
                return $value;
            }],
            [['assignedTo'], 'integer'],
            [
                ['assignedTo'],
                'exist',
                'skipOnError' => false,
                'targetClass' => $userModel::className(),
                'targetAttribute' => ['assignedTo' => 'id']
            ],
            ['status', 'boolean']
        ];

        $rules = ArrayHelper::merge($rules, UserFrom::rules());
        return $rules;
    }

    public function save()
    {
        $ticketThemes = new TicketTheme();
        $ticketMessage = new CreateMessage();

        $ticketThemes->user_from = $this->getUserFrom();
        $ticketThemes->assigned_to = $this->getAssignedTo();
        $ticketThemes->subject = $this->subject;
        $ticketThemes->is_closed = 0;

        if ($ticketThemes->validate())
        {
            $saved = $ticketThemes->save();
        }
        else
        {
            return false;
        }

        $ticketMessage->message = $this->message;
        $ticketMessage->theme_id = $ticketThemes->id;
        $ticketMessage->answered_by = \Yii::$app->user->id;
        $ticketMessage->is_new = 0;

        if ($ticketMessage->validate())
        {
            $ticketMessage->save();
        }

        $this->dialogId = $ticketThemes->id;

        return $saved;
    }
}