<?php

namespace rgen3\tickets\models;

use rgen3\tickets\interfaces\Translation;
use rgen3\tickets\Module;
use yii\db\ActiveRecord;

class TicketStatusTranslation extends ActiveRecord implements Translation
{
    private $language;

    public function init()
    {
        $this->language = \Yii::$app->language;
        parent::init(); // TODO: Change the autogenerated stub
    }

    public static function tableName()
    {
        return '{{ticket_status_translation}}';
    }

    public function rules()
    {
        return [
            [['parent_id'], 'integer'],
            ['language_code', 'in', 'range' => Module::$languages]
        ];
    }

    public function setLanguage($lang)
    {
        $this->language = $lang;
    }

    public function getLanguage()
    {
        return $this->language;
    }

    public function getParent()
    {
        return $this->hasOne(TicketStatus::class, ['parent_id' => 'id']);
    }
}